m

diff --git a/bin/fiat-calculator b/bin/fiat-calculator
--- a/bin/fiat-calculator
+++ b/bin/fiat-calculator
@@ -1,37 +1,16 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 ...
+#h: Usage: fiat-calculator ...
 #h:
 #h: Get currency rates to the dollar with `www.calculator.net`.
 #h:
-#h: ... show                    : Show variables.
-#h: ... list|l                  : List available currencies.
-#h: ... price|p COIN [QUANTITY] : See the price in dollars.
-#h: ... COIN                    : See the price in dollars.
+#h:   show                      Show variables.
+#h:   list|l                    List available currencies.
+#h:   price|p COIN [QUANTITY]   See the price in dollars.
+#h:   COIN                      See the price in dollars.
+#h:
+#h: This program requires `html-lmxml-utils` to function.
 ##:
-. hlog
-. hmain
 fiat_calculator() {
     local cmd="$1"
     shift
@@ -43,13 +22,12 @@ fiat_calculator() {
     esac
 }
 fiat_calculator_show_variables() {
-    printf '%-25s : %s\n' \
-           FIAT_CALCULATOR_URL "${FIAT_CALCULATOR_URL}"
+    echo "FIAT_CALCULATOR_URL : ${FIAT_CALCULATOR_URL}"
 }
 fiat_calculator_calc_variables() {
     FIAT_CALCULATOR_URL="https://www.calculator.net"
 }
-## -----------------------------------------------------------------------------
+## -------------------------------------------------------------------
 fiat_calculator_list() {
     cat <<-EOF
 	AUD: Australian Dollar
@@ -77,7 +55,7 @@ fiat_calculator_price() {
         local fr="`echo "${1}" | tr '[:lower:]' '[:upper:]'`"
         local to="USD"
     else
-        hlog error "Please specify a currency."
+        echo >&2 "error: Please specify a currency."
         return 1
     fi
     ## Forge url.
@@ -91,8 +69,11 @@ fiat_calculator_price() {
     local p="`printf '%s\n' "${h}" | hxnormalize -x -L | hxselect -i -c "${f}" | sed 's|,||g'`"
     echo "${p}"
 }
-
-
-## -----------------------------------------------------------------------------
+## -------------------------------------------------------------------
 fiat_calculator_calc_variables
-hmain -f "fiat-calculator" fiat_calculator "$@"
+if test @"${SCRNAME:-$(basename "$0")}" = @"fiat_calculator"; then
+    case "${1}" in
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0";;
+        *)            fiat_calculator "$@"; exit 0;;
+    esac
+fi
